# -*- coding: utf-8 -*-
"""1463_1로 만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IG7exSQbWqsRYbSVPLY2tEwr2Ta2avOI
"""

##1463_1로 만들기
C= 0 
n = int(input())
Q = [[n]]## 횟수

while True:
  temp = Q.pop(0)
  templist=[]
  if n==1:
    print(0)
    break
  for i in temp:
    templist.append(i-1)
    if i%2==0:
      templist.append(i//2)
    if i%3==0:
      templist.append(i//3)
  if 1 in templist:
    print(C+1)
    break
  else:
    C+=1
    Q.append(templist)